.\" Manpage for ch.
.TH CH 1 "Sep 1, 2020" "1.0" "ch"
.SH NAME
ch \- More than just a cheat sheet - An interactive helper for chmod
.SH SYNOPSIS
ch
.SH DESCRIPTION
ch is a high-level interactive posix shell helper for chmod. It borrows some of the best features from resources found online and brings them back to the terminal with a focus on portability.
.SH OPTIONS
ch does not take any options. However, --help and --version work as expected.
.SH LICENSE
MIT License - \fI\s-1https://choosealicense.com/licenses/mit/\fR
.SH SEE ALSO
chmod(1)
.SH BUGS
Please submit all issues here: \fI\s-1https://github.com/Adobe-Android/chmod-helper/issues/new\fR
.SH AUTHOR
David Brown - \fI\s-1https://github.com/Adobe-Android\fR
.SH HOME
\fI\s-1https://github.com/Adobe-Android/chmod-helper\fR